# Generated by Django 4.1.3 on 2023-11-25 03:16

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(1000, 'Brainstorming is about generating as many ideas as possible. Add more to have a more productive mind map!')], verbose_name='Text')),
                ('mind_map', api.models.MindMapField()),
            ],
        ),
    ]
